import {
  Swords,
  BarChartBig,
  TrendingUp,
  Target,
  Trophy,
  Package,
  User,
  Crosshair,
  Flag,
  Settings,
  Bot,
  Accessibility,
  ZoomIn,
  Contrast,
  Pause,
  Upload,
  Download,
  Trash2,
  ChevronDown,
  Clock,
  Coins,
  Helmet,
  BrainCircuit,
  AreaChart,
  CalendarCheck2,
  Flame,
  Star,
  Zap,
  Gem,
  ArrowRight,
  ChevronRight,
  PlusCircle,
  FileUp,
  FileDown,
  X,
  Copy,
  Info
} from 'lucide-react';

export const Icons = {
  swords: Swords,
  barChart: BarChartBig,
  trendingUp: TrendingUp,
  target: Target,
  trophy: Trophy,
  package: Package,
  user: User,
  crosshair: Crosshair,
  flag: Flag,
  settings: Settings,
  bot: Bot,
  accessibility: Accessibility,
  zoomIn: ZoomIn,
  contrast: Contrast,
  pause: Pause,
  upload: Upload,
  download: Download,
  trash: Trash2,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  clock: Clock,
  coins: Coins,
  helmet: Helmet,
  brain: BrainCircuit,
  areaChart: AreaChart,
  calendarCheck: CalendarCheck2,
  flame: Flame,
  star: Star,
  zap: Zap,
ax: X,
  gem: Gem,
  arrowRight: ArrowRight,
  plusCircle: PlusCircle,
  fileUp: FileUp,
  fileDown: FileDown,
  copy: Copy,
  info: Info
};
